<?php
/**
 * Author: Ted Bowman
 * Date: 9/26/14
 * Time: 12:48 PM
 */

/**
 * Return HTML for form.
 * @param array $form_elements
 *  Array of form elements. Each form element will be passed to form_maker_create_form_element.
 *  @see form_maker_create_form_element().
 * @return string
 *  HTML output.
 */
function form_maker_create_form($form_elements) {

}
/**
 * Return HTML for form element.
 * @param array $element_info
 *  Info about 1 form element.
 *  Keys = '#type', '#title','#default_value'(optional)
 * @return string
 *  HTML output.
 */
function form_maker_create_form_element($element_info) {

}
/**
 * Return HTML form textfield input.
 * @param array $element_info
 *  Info about 1 form element.
 *  Keys = '#type', '#title','#default_value'(optional)
 */
function form_maker_create_textfield($element_info) {

}
/**
 * Return HTML form textarea.
 * @param $element_info
 *  Info about 1 form element.
 *  Keys = '#type', '#title','#default_value'(optional)
 */
function form_maker_create_textarea($element_info) {

}
